### ISSUE TITLE
Gift String Suggestion

### ISSUE THREAD

**Issue by KerrMcF** [BlobEmoji/blobsanta#17]
# String Guidelines
- Strings should be in the general format of `{0} just sent (a/an) <Emoji> <Name> to {1}. <Flavor Text>`.
- Strings must be grammatically correct, safe for work, appropriate, and not include any special formatting (with the exception of emoji formatting.)
- Emojis must be normal unicode or official Blob Emoji. Include the raw emoji for normal unicode emoji or `<:name:id>` formatting for Discord emoji. Only in special/rare cases will other custom emoji be used. 

- [x] All of my suggestions meet these guidelines.

# String Suggestions
*Type your string suggestion(s), following the above guidelines, below the line. Please include intended meaning/explanation for any references.*

*(If you are interested in creating a pull request to implement these suggestions yourself, please read our [Guidelines for Implementating Gift String Suggestions](https://github.com/BlobEmoji/blobsanta/blob/main/CONTRIBUTING.md#guidelines-for-implementating-gift-string-suggestions) after creating your issue.)*

------

- `{0} just sent a 👶 Baby to {1}. Ready to pay child support, {0}?`
- `{0} just sent 👤 {0} to {1}. I think they may be hinting something.`
- `{0} just sent a 🐢 Turtle to {1}. This may take a while.`
- `{0} just sent a 🛸 UFO to {1}. Look out!`
- `{0} just sent 🪐 Saturn to {1}. I didn't know that was allowed?`

**Comment by 7bitlyrus** [comment]
Your second string is missing a name after the emoji, is that intentional?

**Comment by 7bitlyrus** [comment]
> Your second string is missing a name after the emoji, is that intentional?

Oh, I see what you did there.

**Comment by ghost** [comment]
Here's some nitpicks of mine:
```
{0} just sent a 👶 Baby to {1}. Ready to pay child support, {0}?
```
I'm not sure how it should be improved, but I feel like there's room for improvement
```diff
- {0} just sent 👤 {0} to {1}. I think they may be hinting something.
+ {0} just sent 🧑 Themselves to {1}. Maybe they're hinting something?
```
I don't get it, but I feel like the emoji should be replaced with the adult emoji and {0} should just be `Themselves`.
Also the gift strings should ideally be either from a second-person (you) or third-person (they/it) narrator. TL;DR: Avoid "I"
```
{0} just sent a 🐢 Turtle to {1}. This may take a while.
{0} just sent a 🛸 UFO to {1}. Look out!
```
I don't see anything wrong with those two. No changes needed
```diff
- {0} just sent 🪐 Saturn to {1}. I didn't know that was allowed?
+ {0} just sent 🪐 Saturn to {1}. It shouldn't be allowed, but yet, it is.
```
Same as 2nd, avoid "I"

**Comment by 7bitlyrus** [comment]
> ```
> {0} just sent a 👶 Baby to {1}. Ready to pay child support, {0}?
> ```
> 
> I'm not sure how it should be improved, but I feel like there's room for improvement

I do indeed believe that child support isn't exactly a topic that should be in lighthearted joke lines.
