### ISSUE TITLE
Gift String Suggestion

### ISSUE THREAD

**Issue by eah1759** [BlobEmoji/blobsanta#20]
# String Guidelines
- Strings should be in the general format of `{0} just sent (a/an) <Emoji> <Name> to {1}. <Flavor Text>`.
- Strings must be grammatically correct, safe for work, appropriate, and not include any special formatting (with the exception of emoji formatting.)
- Emojis must be normal unicode or official Blob Emoji. Include the raw emoji for normal unicode emoji or `<:name:id>` formatting for Discord emoji. Only in special/rare cases will other custom emoji be used. 

- [x] All of my suggestions meet these guidelines.

# String Suggestions
*Type your string suggestion(s), following the above guidelines, below the line. Please include intended meaning/explanation for any references.*

*(If you are interested in creating a pull request to implement these suggestions yourself, please read our [Guidelines for Implementating Gift String Suggestions](https://github.com/BlobEmoji/blobsanta/blob/main/CONTRIBUTING.md#guidelines-for-implementating-gift-string-suggestions) after creating your issue.)*

------

- `{0} just sent a <:googlegiftorange:782336872356642817> Gift to {1}. In order to understand recursion, one must first understand recursion.`

**Comment by ghost** [comment]
The only thing that I think it should be changed is to replace the custom emoji with an Unicode gift one, otherwise, it seems good! I'd say replace it with googlegift but it hasn't been added yet

**Comment by xela-zone** [comment]
Maybe modify the string posted to allow filling the displayed gift? Allowing proper recursion?
