### ISSUE TITLE
Gift String Suggestion

### ISSUE THREAD

**Issue by Vulpix037** [BlobEmoji/blobsanta#23]
# String Guidelines
- Strings should be in the general format of `{0} just sent (a/an) <Emoji> <Name> to {1}. <Flavor Text>`.
- Strings must be grammatically correct, safe for work, appropriate, and not include any special formatting (with the exception of emoji formatting.)
- Emojis must be normal unicode or official Blob Emoji. Include the raw emoji for normal unicode emoji or `<:name:id>` formatting for Discord emoji. Only in special/rare cases will other custom emoji be used. 

- [x] All of my suggestions meet these guidelines.

# String Suggestions
*Type your string suggestion(s), following the above guidelines, below the line. Please include intended meaning/explanation for any references.*

*(If you are interested in creating a pull request to implement these suggestions yourself, please read our [Guidelines for Implementating Gift String Suggestions](https://github.com/BlobEmoji/blobsanta/blob/main/CONTRIBUTING.md#guidelines-for-implementating-gift-string-suggestions) after creating your issue.)*

------

- `{0} just sent a <a:ablobtoiletflush:614485943377985566> Toilet to {1}. Don't forget to flush it!` 
- `{0} just sent a 💩 Pile of Poo to {1}. Uh-oh, stinky!`

**Comment by ghost** [comment]
The strings follow the format properly, I see no issues here, however, these strings seems to be a little questionable, I don't know if it should be approved

**Comment by ghost** [comment]
I guess the toilet humor shall be... ..._flushed_. 🥁🥁🥁
